<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <fields>
        <fullName>Class_Origination__c</fullName>
        <description>*Possible* apex class exception thrown from</description>
        <externalId>false</externalId>
        <inlineHelpText>*Possible* apex class exception thrown from</inlineHelpText>
        <label>Class Origination</label>
        <length>255</length>
        <required>false</required>
        <trackTrending>false</trackTrending>
        <type>Text</type>
        <unique>false</unique>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>Line Number exception occurred</description>
        <externalId>false</externalId>
        <inlineHelpText>Line Number exception occurred</inlineHelpText>
        <label>Line Number</label>
        <precision>18</precision>
        <required>false</required>
        <scale>0</scale>
        <trackTrending>false</trackTrending>
        <type>Number</type>
        <unique>false</unique>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message passed by the Exception</description>
        <externalId>false</externalId>
        <inlineHelpText>Message passed by the Exception</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <trackTrending>false</trackTrending>
        <type>LongTextArea</type>
        <visibleLines>3</visibleLines>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Stack Trace passed by the Exception</description>
        <externalId>false</externalId>
        <inlineHelpText>Stack Trace passed by the Exception</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <trackTrending>false</trackTrending>
        <type>LongTextArea</type>
        <visibleLines>3</visibleLines>
    </fields>
    <fields>
        <fullName>Trigger_Origination__c</fullName>
        <description>*Possible* apex trigger exception thrown from</description>
        <externalId>false</externalId>
        <inlineHelpText>*Possible* apex trigger exception thrown from</inlineHelpText>
        <label>Trigger Origination</label>
        <length>255</length>
        <required>false</required>
        <trackTrending>false</trackTrending>
        <type>Text</type>
        <unique>false</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Exception Type</description>
        <externalId>false</externalId>
        <inlineHelpText>Exception Type</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>false</required>
        <trackTrending>false</trackTrending>
        <type>Text</type>
        <unique>false</unique>
    </fields>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Type__c</columns>
        <columns>Line_Number__c</columns>
        <columns>Message__c</columns>
        <columns>Stack_Trace__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
</CustomObject>
